#line 1 "cscanner.cxx"

#line 3 "cscanner.cxx"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[326] =
    {   0,
        0,    0,  104,  102,  101,  101,   89,  102,   54,   95,
       88,  102,   83,   84,   93,   92,   80,   91,   87,   94,
       44,   45,   81,   77,   96,   82,   97,  100,   42,   42,
       85,   86,   98,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   78,
       99,   79,   90,   76,    0,   53,    0,   54,   62,   79,
       71,   63,    0,    0,   60,   68,   58,   69,   59,   70,
        0,   48,    1,    2,   61,   49,   44,    0,    0,   44,
       44,    0,   44,   45,   45,   45,   45,   86,   78,   85,
       67,   73,   75,   74,   66,   42,    0,    0,   64,   42,

       42,   42,   42,   42,   42,   42,   42,   42,   12,   42,
       42,   42,   42,   42,   42,   42,   20,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   65,
       72,   46,   55,    0,   48,    2,   48,    0,   49,    0,
       47,   44,   44,   44,   44,    0,   43,   45,   45,   45,
       45,   57,   56,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   18,   42,
       42,   23,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,    0,
       48,    0,   48,    0,   49,   47,   44,    0,    0,   43,

        0,   43,   43,   45,   42,   42,   42,    3,   42,    6,
        7,   42,   42,   42,   42,   14,   15,   42,   42,   42,
       19,   42,   24,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   40,   42,   42,   42,   37,   42,   42,    0,
       48,    0,    0,    0,   43,   43,    0,   50,   43,   43,
        4,   42,   42,    5,    9,   42,   42,   42,   42,   41,
       17,   42,   42,   42,   42,   28,   42,   42,   42,   42,
       42,   42,   35,   42,   42,   39,    0,   51,    0,    0,
       52,   50,   43,   42,   42,   42,   42,   13,   16,   22,
       42,   42,   27,   29,   30,   31,   32,   33,   42,   42,

       42,   51,    0,   51,   52,   42,   42,   42,   11,   42,
       42,   34,   42,   42,   51,    8,   42,   10,   25,   26,
       36,   38,   42,   21,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   35,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    6,
        1,    1,    1,    1,    1,    1,    6,    6,    6,    6,
        6,    7,    7,    7,    8,    7,    7,    1,    1,    1,
        1,    7,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    8,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[334] =
    {   0,
        0,    0,  558,  559,  559,  559,  533,   66,    0,   48,
       66,  517,  559,  559,  531,   62,  559,   63,   61,   72,
       90,   81,  529,  559,   95,  529,   58,  559,    0,   86,
      559,  559,  528,   65,  490,  492,   79,   29,   59,   88,
      493,   77,  492,  500,   89,   80,  491,  489,  494,  559,
       68,  559,  559,  559,  108,  559,    0,    0,  559,  559,
      559,  559,   94,  534,  559,  559,  559,  559,  559,  559,
      526,  137,  559,    0,  559,  144,  180,  185,  168,  112,
      116,  525,  141,  201,  146,  119,  173,  559,  559,  559,
      516,  559,  559,  559,  515,    0,  154,  499,  559,  481,

      480,  481,  474,  486,  473,  488,  475,  481,  467,  468,
      465,  465,  471,  467,  464,  461,    0,  105,  465,  163,
      463,   55,  118,  467,  456,  459,  177,  155,  464,  559,
      559,  559,  559,  225,  559,    0,  233,  253,  559,  237,
      256,  134,  559,  480,  460,    0,  249,  188,  559,  478,
      458,  559,  559,  454,  455,  465,  451,  463,  458,  446,
      170,  460,  458,  454,  446,  452,  439,  454,    0,  440,
      444,    0,  445,  442,  432,  430,  432,  434,  441,  427,
      425,  425,  437,  436,  425,  421,  416,  418,  400,  240,
      274,  298,  559,  259,  281,  559,  559,  154,  190,  262,

      306,  126,  267,  559,  399,  388,  392,    0,  388,    0,
        0,  379,  387,  375,  382,    0,    0,  376,  386,  372,
        0,  376,    0,  371,  371,  370,  367,  379,  369,  371,
      376,  373,    0,  371,  361,  366,    0,  354,  366,  312,
      317,  325,  204,  334,  234,  559,  337,  340,  378,  358,
        0,  357,  355,    0,    0,  349,  350,  353,  340,    0,
        0,  347,  332,  336,  331,    0,  335,  325,  327,  309,
      314,  303,    0,  291,  291,    0,  343,  348,  365,  357,
      371,  559,  559,  294,  284,  272,  254,    0,    0,    0,
      260,  252,    0,    0,    0,    0,    0,    0,  243,  242,

      235,  559,  379,  389,  559,  218,  226,  203,    0,  188,
      182,    0,  172,  166,  559,    0,  108,    0,    0,    0,
        0,    0,   65,    0,  559,  442,  450,  458,  461,  469,
      473,  101,  474
    } ;

static const flex_int16_t yy_def[334] =
    {   0,
      325,    1,  325,  325,  325,  325,  325,  326,  327,  325,
      325,  328,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  329,  329,
      325,  325,  325,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  325,
      325,  325,  325,  325,  326,  325,  326,  327,  325,  325,
      325,  325,  328,  328,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  330,  325,  325,  325,  325,  325,  325,
      325,  331,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  329,  326,  328,  325,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  325,
      325,  325,  325,  325,  325,  330,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  332,  331,  325,  325,  325,
      325,  325,  325,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  325,
      325,  325,  325,  325,  325,  325,  325,  332,  333,  325,

      325,  325,  325,  325,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  325,
      325,  325,  333,  325,  325,  325,  325,  325,  325,  325,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  325,  325,  325,  325,
      325,  325,  325,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  325,  325,  325,  325,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  325,  329,  329,  329,  329,  329,
      329,  329,  329,  329,    0,  325,  325,  325,  325,  325,
      325,  325,  325
    } ;

static const flex_int16_t yy_nxt[630] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   29,   30,   29,   29,   29,   31,    4,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   29,
       42,   29,   43,   29,   29,   29,   29,   44,   45,   46,
       47,   48,   49,   29,   29,   29,   50,   51,   52,   53,
       56,   59,   60,   61,   66,  108,   71,   68,   72,   72,
       72,   94,   95,   73,  109,   67,   69,   70,   74,   62,
       97,  130,  100,  101,   98,   75,   76,  102,   84,   84,

       84,   89,  132,  178,   57,   76,  198,   77,   77,   78,
       79,  110,   56,  111,   85,   90,   86,   91,   92,   79,
      179,  105,  112,   80,  117,   81,   82,   79,  106,  324,
      113,  118,   64,   87,  107,  131,   79,  125,  121,  122,
      114,   86,   83,  115,  126,  142,   57,  143,  123,  144,
       81,  124,  150,   82,   72,   72,   72,  171,   56,  249,
      180,  137,  137,  137,  172,  323,  134,  135,  145,  143,
      135,  151,  143,  138,  139,  181,  143,  139,  250,  148,
      140,  149,  140,  134,  135,  141,  141,  141,  242,  135,
      138,  139,   57,  142,  143,   76,  139,   77,   77,   78,

       76,  143,   78,   78,   78,  187,  149,  188,  149,   79,
      242,  174,  322,   80,   79,   81,   76,  321,   84,   84,
       84,  175,  176,  149,  244,  148,   79,  185,  212,  213,
       79,   79,   83,  149,   85,  186,   86,  190,  279,  190,
       81,  320,  191,  191,  191,  319,  244,   79,  149,  318,
      137,  137,  137,   87,  141,  141,  141,  191,  191,  191,
      279,   86,  192,  193,  199,  194,  193,  194,  317,  246,
      195,  195,  195,  141,  141,  141,  195,  195,  195,  192,
      193,  316,  200,  201,  202,  193,  196,  314,  313,  196,
      312,  191,  191,  191,  246,  245,  311,  246,  195,  195,

      195,  203,  246,  196,  135,  201,  310,  135,  196,  202,
      240,  139,  240,  309,  139,  241,  241,  241,  247,  245,
      247,  135,  246,  248,  248,  248,  135,  246,  139,  241,
      241,  241,  308,  139,  241,  241,  241,  277,  307,  277,
      306,  301,  278,  278,  278,  300,  280,  193,  280,  299,
      193,  281,  281,  281,  248,  248,  248,  248,  248,  248,
      278,  278,  278,  298,  193,  278,  278,  278,  297,  193,
      282,  296,  295,  282,  281,  281,  281,  303,  302,  303,
      294,  302,  304,  304,  304,  293,  292,  282,  281,  281,
      281,  291,  282,  290,  289,  302,  304,  304,  304,  288,

      302,  305,  287,  286,  305,  285,  304,  304,  304,  284,
      283,  283,  276,  275,  274,  273,  272,  271,  305,  315,
      270,  269,  315,  305,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  315,  256,  255,  254,
      253,  315,   55,   55,  252,   55,   55,   55,   55,   55,
       58,  251,  239,   58,   58,   58,   58,   58,   63,   63,
      238,  237,   63,   63,   63,   63,   96,   96,   96,  136,
      136,  236,  136,  136,  136,  136,  136,  147,  147,  243,
      235,  243,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,

      216,  215,  214,  211,  210,  209,  208,  207,  206,  205,
      204,  204,  197,  197,  189,  184,  183,  182,  177,  173,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,   64,  153,  152,
      146,  133,   63,  129,  128,  127,  120,  119,  116,  104,
      103,   99,   93,   88,   65,   64,   54,  325,    3,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325
    } ;

static const flex_int16_t yy_chk[630] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        8,   10,   10,   11,   16,   38,   19,   18,   19,   19,
       19,   27,   27,   20,   38,   16,   18,   18,   20,   11,
       30,   51,   34,   34,   30,   20,   22,   34,   22,   22,

       22,   25,   63,  122,    8,   21,  332,   21,   21,   21,
       22,   39,   55,   39,   22,   25,   22,   25,   25,   21,
      122,   37,   39,   21,   42,   21,   21,   22,   37,  323,
       40,   42,   63,   22,   37,   51,   21,   46,   45,   45,
       40,   22,   21,   40,   46,   80,   55,   80,   45,   81,
       21,   45,   86,   21,   72,   72,   72,  118,   97,  202,
      123,   76,   76,   76,  118,  317,   72,   72,   81,  142,
       72,   86,   80,   76,   76,  123,   83,   76,  202,   85,
       79,   85,   79,   72,   72,   79,   79,   79,  198,   72,
       76,   76,   97,   83,  142,   77,   76,   77,   77,   77,

       78,   83,   78,   78,   78,  128,   85,  128,   87,   77,
      198,  120,  314,   77,   78,   77,   84,  313,   84,   84,
       84,  120,  120,  148,  199,   87,   77,  127,  161,  161,
       84,   78,   77,   87,   84,  127,   84,  134,  243,  134,
       77,  311,  134,  134,  134,  310,  199,   84,  148,  308,
      137,  137,  137,   84,  140,  140,  140,  190,  190,  190,
      243,   84,  137,  137,  147,  138,  137,  138,  307,  245,
      138,  138,  138,  141,  141,  141,  194,  194,  194,  137,
      137,  306,  147,  147,  147,  137,  141,  301,  300,  141,
      299,  191,  191,  191,  245,  200,  292,  200,  195,  195,

      195,  147,  203,  141,  191,  147,  291,  191,  141,  147,
      192,  195,  192,  287,  195,  192,  192,  192,  201,  203,
      201,  191,  200,  201,  201,  201,  191,  203,  195,  240,
      240,  240,  286,  195,  241,  241,  241,  242,  285,  242,
      284,  275,  242,  242,  242,  274,  244,  241,  244,  272,
      241,  244,  244,  244,  247,  247,  247,  248,  248,  248,
      277,  277,  277,  271,  241,  278,  278,  278,  270,  241,
      248,  269,  268,  248,  280,  280,  280,  279,  278,  279,
      267,  278,  279,  279,  279,  265,  264,  248,  281,  281,
      281,  263,  248,  262,  259,  278,  303,  303,  303,  258,

      278,  281,  257,  256,  281,  253,  304,  304,  304,  252,
      250,  249,  239,  238,  236,  235,  234,  232,  281,  304,
      231,  230,  304,  281,  229,  228,  227,  226,  225,  224,
      222,  220,  219,  218,  215,  214,  304,  213,  212,  209,
      207,  304,  326,  326,  206,  326,  326,  326,  326,  326,
      327,  205,  189,  327,  327,  327,  327,  327,  328,  328,
      188,  187,  328,  328,  328,  328,  329,  329,  329,  330,
      330,  186,  330,  330,  330,  330,  330,  331,  331,  333,
      185,  333,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  171,  170,  168,  167,  166,  165,

      164,  163,  162,  160,  159,  158,  157,  156,  155,  154,
      151,  150,  145,  144,  129,  126,  125,  124,  121,  119,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   98,   95,   91,
       82,   71,   64,   49,   48,   47,   44,   43,   41,   36,
       35,   33,   26,   23,   15,   12,    7,    3,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "clex.y"
/* Lex file based on this source:
 * http://www.quut.com/c/ANSI-C-grammar-l-1999.html
 * Thanks!
 */
#line 20 "clex.y"
#include <stdio.h>
#include <string>

namespace clex
{
	enum FORMAT_TYPE_ENUM
	{
		INVALID	=	0,
		COMMENT,
		SINGLE_LINE_COMMENT,
		PREPROCESSOR_START,
		PREPROCESSOR,
		KEYWORD_GROUP_A,
		KEYWORD_GROUP_B,
		KEYWORD_GROUP_C,
		KEYWORD_GROUP_D,
		PUNCTUATION,
		NUMBER,
		STRING,
		FORMAT_TYPES_COUNT,
	};
}
using namespace clex;

static void emit(int c, yyscan_t yyscanner);
static void emit_raw_string(const char * s, yyscan_t yyscanner);
static void emit_escaped(int c, yyscan_t yyscanner);
static void emit_format_begin(enum FORMAT_TYPE_ENUM format, yyscan_t yyscanner);
static void emit_format_end(yyscan_t yyscanner);
static void emit_yytext(yyscan_t yyscanner);
static void emit_formatted_yytext(enum FORMAT_TYPE_ENUM format, yyscan_t yyscanner);
static void comment(yyscan_t yyscanner);
static void preprocessor(yyscan_t yyscanner);

#line 709 "cscanner.cxx"
#line 710 "cscanner.cxx"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE std::string *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 56 "clex.y"

#line 970 "cscanner.cxx"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 326 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 559 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "clex.y"
{ /* */ comment(yyscanner); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "clex.y"
{ emit_formatted_yytext(SINGLE_LINE_COMMENT, yyscanner); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_C, yyscanner); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_C, yyscanner); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 77 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 78 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 79 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 80 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_C, yyscanner); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 81 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 83 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_C, yyscanner); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 86 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 88 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 89 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 90 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 92 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_C, yyscanner); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_B, yyscanner); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 96 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_C, yyscanner); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_A, yyscanner); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "clex.y"
{ emit_formatted_yytext(KEYWORD_GROUP_D, yyscanner); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "clex.y"
{ emit_formatted_yytext(STRING, yyscanner); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "clex.y"
{ emit_formatted_yytext(NUMBER, yyscanner); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 117 "clex.y"
{ emit_formatted_yytext(STRING, yyscanner); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "clex.y"
{ preprocessor(yyscanner); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 121 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 125 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 126 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 127 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 128 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 129 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 130 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 131 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 132 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 133 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 134 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 135 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 136 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 137 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 138 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 139 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 140 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 141 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 142 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 143 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 144 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 145 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 146 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 147 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 148 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 149 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 150 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 151 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 152 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 153 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 154 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 155 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 156 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 157 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 158 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 159 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 160 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 161 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 162 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 163 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 164 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 165 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 166 "clex.y"
{ emit_formatted_yytext(PUNCTUATION, yyscanner); }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 168 "clex.y"
{ emit(* yytext, yyscanner); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 169 "clex.y"
{ emit(* yytext, yyscanner); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 171 "clex.y"
ECHO;
	YY_BREAK
#line 1543 "cscanner.cxx"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 326 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 326 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 325);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 171 "clex.y"


static void emit(int c, yyscan_t yyscanner)
{
	yyget_extra(yyscanner)->operator+=(c);
}

static void emit_raw_string(const char * s, yyscan_t yyscanner)
{
	while (* s)
		emit(* s ++, yyscanner);
}


static void emit_escaped(int c, yyscan_t yyscanner)
{
	switch (c)
	{
		default: emit(c, yyscanner); break;
		case '<': emit_raw_string("&lt;", yyscanner); break;
		case '>': emit_raw_string("&gt;", yyscanner); break;
		case '&': emit_raw_string("&amp;", yyscanner); break;
	}
}

static void emit_format_begin(enum FORMAT_TYPE_ENUM format, yyscan_t yyscanner)
{
static const char * format_strings[FORMAT_TYPES_COUNT] = {
	[FORMAT_TYPE_ENUM::INVALID] =			"inv",
	[FORMAT_TYPE_ENUM::COMMENT] =			"com",
	[FORMAT_TYPE_ENUM::SINGLE_LINE_COMMENT] =	"slc",
	[FORMAT_TYPE_ENUM::PREPROCESSOR_START] =	"pps",
	[FORMAT_TYPE_ENUM::PREPROCESSOR] =		"ppc",
	[FORMAT_TYPE_ENUM::KEYWORD_GROUP_A] =		"kwa",
	[FORMAT_TYPE_ENUM::KEYWORD_GROUP_B] =		"kwb",
	[FORMAT_TYPE_ENUM::KEYWORD_GROUP_C] =		"kwc",
	[FORMAT_TYPE_ENUM::KEYWORD_GROUP_D] =		"kwd",
	[FORMAT_TYPE_ENUM::PUNCTUATION] =		"opt",
	[FORMAT_TYPE_ENUM::NUMBER] =			"num",
	[FORMAT_TYPE_ENUM::STRING] =			"str",
};
	if (format < 0 || format >= FORMAT_TYPES_COUNT)
		format = FORMAT_TYPE_ENUM::INVALID;

	emit_raw_string("<span class=\"hl ", yyscanner);
	emit_raw_string(format_strings[format], yyscanner);
	emit_raw_string("\">", yyscanner);
}

static void emit_format_end(yyscan_t yyscanner)
{
	emit_raw_string("</span>", yyscanner);
}

static void emit_yytext(yyscan_t yyscanner)
{
	const char * p = yyget_text(yyscanner);
	while (* p)
		emit_escaped(* p ++, yyscanner);
}

static void emit_formatted_yytext(enum FORMAT_TYPE_ENUM format, yyscan_t yyscanner)
{
	emit_format_begin(format, yyscanner);
	emit_yytext(yyscanner);
	emit_format_end(yyscanner);
}

/*! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * THIS IS BUGGY, IT CRASHES BADLY IN CASE OF UNTERMINATED COMMENTS
 * DEBUG THIS
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! */
static void comment(yyscan_t yyscanner)
{
	char c, prev = 0;
	emit_format_begin(FORMAT_TYPE_ENUM::COMMENT, yyscanner);
	emit_yytext(yyscanner);
  
	while ((c = yyinput(yyscanner)) != 0)      /* (EOF maps to 0) */
	{
		if (c == '/' && prev == '*')
		{
			emit_escaped(c, yyscanner);
			emit_format_end(yyscanner);
			return;
		}
		if (c == '\n')
		{
			emit_format_end(yyscanner);
			emit_escaped(c, yyscanner);
			emit_format_begin(FORMAT_TYPE_ENUM::COMMENT, yyscanner);
		}
		else
			emit_escaped(c, yyscanner);
		prev = c;
	}
	emit_raw_string("unterminated comment", yyscanner);
	emit_format_end(yyscanner);
}

/*! \todo This is broken for dos line endings (<CR><LF>). */
static void preprocessor(yyscan_t yyscanner)
{
	char c, prev = 0;
	emit_format_begin(FORMAT_TYPE_ENUM::PREPROCESSOR_START, yyscanner);
	emit_yytext(yyscanner);
	emit_format_end(yyscanner);
	emit_format_begin(FORMAT_TYPE_ENUM::PREPROCESSOR, yyscanner);
  
	while ((c = yyinput(yyscanner)) != 0)      /* (EOF maps to 0) */
	{
		if (c == '\n' && prev == '\\')
		{
			emit_format_end(yyscanner);
			emit(c, yyscanner);
			emit_format_begin(FORMAT_TYPE_ENUM::PREPROCESSOR, yyscanner);
		}
		else if (c == '\n')
		{
			emit_format_end(yyscanner);
			emit_escaped(c, yyscanner);
			return;
		}
		else
			emit_escaped(c, yyscanner);
		prev = c;
	}
	emit_format_end(yyscanner);
}


#ifdef CLEX_TEST_DRIVE
#include <stdio.h>
#define MAX_SCANNED_SOURCE_CODE_FILE_SIZE	10 * 1024 * 1024
/* Reserve one byte for the string null terminator. */
static char test_string[MAX_SCANNED_SOURCE_CODE_FILE_SIZE + 1];

static const char * html_header =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"<meta charset=\"ISO-8859-1\">\n"
"<title>Source file</title>\n"
"<link rel=\"stylesheet\" type=\"text/css\" href=\"highlight.css\">\n"
"</head>\n"
"<body class=\"hl\">\n"
"<pre class=\"hl\">"
;

static const char * html_footer =
"</pre>\n"
"</body>\n"
"</html>\n"
"<!--HTML generated by XXX: todo - put an appropriate reference here-->"
;

int main(int argc, char * argv[])
{
FILE * infile;

	if (argc != 2)
	{
		printf("No source code file specified.\nUsage: %s <source-code-file-to-scan>\n", * argv);
		exit(1);
	}
	if (!(infile = fopen(argv[1], "r+b")))
	{
		printf("Failed to open input file %s\n", argv[1]);
		exit(2);
	}

	fread(test_string, 1, MAX_SCANNED_SOURCE_CODE_FILE_SIZE, infile);
	fclose(infile);

	yyscan_t scanner;
	std::string s;
	yylex_init_extra(& s, &scanner);

	s = html_header;
	yy_scan_string(test_string, scanner);
	yylex(scanner);
	yylex_destroy(scanner);
	s += html_footer;
	printf("%s", s.c_str());
	return 0;
}
#endif


